import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import Navbar from "../components/Navbar";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Math Game</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex">
        <Navbar className="flex"/>
      </main>
    </>
  );
};

export default Home;
