import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import Navbar from "../components/Navbar";

import Numpad from "../components/numpad/Numpad";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Math Game</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col h-screen">
        <header>
          <Navbar />
        </header>
        <main className="flex-grow">
          <Numpad />
        </main>
      </div>
    </>
  );
};

export default Home;
