
import "@/styles/style.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import HeaderLayout from "Macaca/packages/ui/src/components/layouts/HeaderLayout";
import { ThemeProvider } from "Macaca/packages/ui/src/components/ThemeProvider";

const themes = ["dark", "light", "system"];
export type Theme = (typeof themes)[number];

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

// TODO: strip out clerk
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <TRPCReactProvider>
        <html lang="en" className={`${GeistSans.variable}`}>
          <body>
            <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
              <HeaderLayout>{children}</HeaderLayout>
            </ThemeProvider>
          </body>
        </html>
    </TRPCReactProvider>
  );
}
